version: "3"

services:
  django:
    build: .
    command: "/start.sh"
    volumes:
      - .:/usr/src/app
      - /Volumes/scripts:/Volumes/scripts
    ports:
      - "8000:8000"
    depends_on:
      - postgres
  postgres:
    image: postgres:latest
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - PGPASSWORD=postgres
  redis:
    image: redis:latest
  celery:
    build: .
    command: celery -A script_executor worker -B -l INFO
    volumes:
      - .:/usr/src/app
      - /Volumes/scripts:/Volumes/scripts
    depends_on:
      - redis
