# Generated by Django 3.2.4 on 2021-06-06 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CoreConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scripts_path', models.CharField(max_length=255, verbose_name='Директория со скриптами')),
            ],
            options={
                'verbose_name': 'Основные настройки',
            },
        ),
    ]
