# Generated by Django 3.2.4 on 2021-06-12 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_rename_coreconfig_appconfiguration'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExecutableFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(max_length=255, verbose_name='Имя файла')),
                ('content', models.TextField(verbose_name='Содердимое файла')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Обновлён')),
            ],
            options={
                'verbose_name': 'Исполняемый файл',
                'verbose_name_plural': 'Исполняемые файлы',
            },
        ),
    ]
